server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端实例名称
  client:
    register-with-eureka: false #表示不像注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例,并不区检索服务
    service-url:
    #集群指向其他eureka
      #defaultZone: http://eureka7002.com:7002/eureka/
    #单机就是自己
      defaultZone: http://eureka7001.com:7001/eureka/
  #server:
    #关闭自我保护机制，保证不可用服务被及时剔除
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 2000
