server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          # uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由

        - id: payment_route2
          # uri: http://localhost:8001
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**  #断言,路径相匹配的进行路由
            #- After=2020-08-20T16:23:32.856+08:00[Asia/Shanghai]  #指定时间后才能访问(After)
            #- Before=2020-06-17T11:53:40.325+08:00[Asia/Shanghai]  #指定时间前才能访问（Before）
            #- Between=2020-06-17T11:53:40.325+08:00[Asia/Shanghai],2020-06-17T12:53:40.325+08:00[Asia/Shanghai]  #指定时间内才能访问（Between）
            #- Cookie=username,hgj  #带Cookie，并且username的值为hgj
            #- Header=X-Request-Id, \d+   #请求头要有 X-Request-Id属性并且值为整数的正则表达式
            #- Host=**.hgj.com	#Host: xxx.angenin.com 请求是Host必须有**.angenin.com
            #- Method=GET,POST	#规定请求方式
            #- Query=username, \d+   #url请求地址必须带上username参数，并且值必须为整数

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
